### ISSUE TITLE
ERROR: Failed to enumerate xbows keyboard device

### ISSUE THREAD

**Issue by slk500** [jlquinn/xbows-driver#15]
I have X-Bows Nature Ergonomic Mechanical Keyboard & Debian 10. After command build/src/kbdtest2 share/test-driver-layer.yaml I have this error 'ERROR: Failed to enumerate xbows keyboard device'. Any hints?
Thank You for your hard work & sharing.

**Comment by jlquinn** [comment]
@slk500 I only developed this code for the original version of the xbows keyboard.  It looks for vendor 0x1ea7 and product id 0x0907.  Your keyboard probably has a different product id, though I expect it to have the same vendor id.  If it's a different product id, chances are the controller is completely different, unfortunately.

You can check by using lsusb to see the vendor:product code.

**Comment by slk500** [comment]
Bus 001 Device 008: ID feed:1226

**Comment by peterhoeg** [comment]
@slk500 `feed:1226` is the new range that supports QMK. You don't need this project.

**Comment by slk500** [comment]
@peterhoeg ok, great. thx for the tip.
