### ISSUE TITLE
kbdtest2 gives ERROR: Failed to enumerate xbows keyboard device

### ISSUE THREAD

**Issue by singletS** [jlquinn/xbows-driver#17]
Debian 11 user here. After wrestling a bit with #16, I compiled hdapi from its github repository, and was then able to compile x-bows driver/executables without errors. However when I run kdbtest2 (or kdbtest) I get: ` ERROR: Failed to enumerate xbows keyboard device`

When the keyboard is connected, dmesg gives about a dozen lines for the usb device, xinput recognizes it (both as a keyboard and mouse(?)), and the keyboard works fine. It looks like the driver should be able to find the usb device as described in xbows.cc comment around line 85.

Is there something I'm missing? Perhaps a conflict between the system version of hdapi and the 'local' one?
Thanks

**Comment by peterhoeg** [comment]
which xbows keyboard do you have? This repo is only for the old non-QMK keyboards.

**Comment by singletS** [comment]
I should have mentioned this...it's the X-bows "lite".

**Comment by peterhoeg** [comment]
What does `lsusb` say the ids are for the keyboard?

**Comment by singletS** [comment]
Thanks for the followup, but I've moved to a QMK capable keyboard.
